tommaso_foo_insert:
    pattern:  /insert/{name}/{surname}/{birthdate}
    defaults: { _controller: TommasoFooBundle:Default:insert }
    
tommaso_foo_list:
    pattern:  /list
    defaults: { _controller: TommasoFooBundle:Default:list }
