parameters:
#    tommaso_foo.example.class: Tommaso\FooBundle\Example

services:
#    tommaso_foo.example:
#        class: %tommaso_foo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
